version: "3"

services:
  app:
    build: .
    container_name: "api_github_actions_aws"
    image: node:16.13.1
    ports:
      - "3333:3333"
    volumes:
      - ./:/user/app
      - /user/app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - api_github_actions_aws-network

networks:
  api_github_actions_aws-network:
    driver: bridge
